#Message Sent to Console When Command Cannot Be Run By Console
errorMessage: '&3&bInvsee &7&l> &4You are unable to execute this command!'

#Message Sent to Player When Missing Permissions
permissionMessage: '&3&bInvsee &7&l> &4You do not have permission to run this command!'

#Message Sent When Player is Not Online
playerOffline: '&3&bInvsee &7&l> &4That player is offline!'

#Message sent when enderchest opened
enderchestOpened: '&3&bInvsee &7&l> &aEnderchest Opened!'

#Message sent when inventory opened
inventoryOpened: '&3&bInvsee &7&l> &aInventory Opened!'

#Message Sent When Command is Missing Arguments
missingArguments: '&3&bInvsee &7&l> &4Command Missing Arguments!'

#Message Sent When Player is Frozen
playerFrozen: '&3&bInvsee &7&l> &aPlayer Has Been Frozen!'

#Message Sent When Player is UnFrozen
playerUnfrozen: '&3&bInvsee &7&l> &aPlayer Has Been Unfrozen!'

#Message Sent When Frozen Player Moves
youFrozen: '&3&bInvsee &7&l> &4You are frozen!'